const router = require('express').Router()
const Todo = require('../controllers/todo')
const User = require('../controllers/user')
const {authenticate,authorize} = require('../middlewares/auth')
router.post('/api/signin',User.signIn)
router.post('/api/signup',User.signUp)
router.use(authenticate)
router.post('/api/todos',Todo.create)
router.get('/api/todos',Todo.getAll)
router.get('/api/todos/:id',authorize ,Todo.getByPk)
router.delete('/api/todos/:id',authorize, Todo.delete)
router.put('/api/todos/:id',authorize, Todo.update)
router.patch('/api/todos/:id',authorize, Todo.update)
module.exports = router